{
 "title": "Device iRules",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "query": {
     "query": "label_values(f5_system_state_up_ratio,job)"
    }
   },
   {
    "name": "rule",
    "query": {
     "query": "label_values(f5_rule_executions_total{job=\"$device_name\"},f5_rule_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 10 iRules By Approx. Cycles Used [24h]",
   "type": "barchart",
   "description": "(Average Cycles / Execution) *E(xecutions Last 24 Hours)",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "topk(10, max by(f5_rule_name) (f5_rule_average_cycles{job=\"$device_name\"}) * max by(f5_rule_name) (increase(f5_rule_executions_total{job=\"$device_name\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 iRules By Cycles Per Execution",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "topk(10, max by(f5_rule_name) (f5_rule_average_cycles{job=\"$device_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Rules By Executions",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, max by(f5_rule_name) (f5_rule_executions_total{job=\"$device_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rule Execution Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Ex. / s" } },
   "targets": [
    {
     "expr": "max by(f5_rule_name) (rate(f5_rule_executions_total{job=\"$device_name\", f5_rule_name=~\"$rule\"}[$__rate_interval]))",
     "legendFormat": "{{f5_rule_name}}"
    }
   ]
  },
  {
   "title": "Rule Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Fail/s" } },
   "targets": [
    {
     "expr": "max by(f5_rule_name) (rate(f5_rule_failures_total{job=\"$device_name\", f5_rule_name=~\"$rule\"}[$__rate_interval]))",
     "legendFormat": "{{f5_rule_name}}"
    }
   ]
  },
  {
   "title": "Rule Abort Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Fail/s" } },
   "targets": [
    {
     "expr": "max by(f5_rule_name) (rate(f5_rule_aborts_total{job=\"$device_name\", f5_rule_name=~\"$rule\"}[$__rate_interval]))",
     "legendFormat": "{{f5_rule_name}}"
    }
   ]
  },
  { "title": "Rule Event Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Executions by Event Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_rule_executions_total{job=\"$device_name\", f5_rule_name=~\"$rule\"}",
     "legendFormat": "{{f5_rule_name}} - {{f5_rule_event_type}}"
    }
   ]
  },
  {
   "title": "Failures by Event Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_rule_failures_total{job=\"$device_name\", f5_rule_name=~\"$rule\"}",
     "legendFormat": "{{f5_rule_name}} - {{f5_rule_event_type}}"
    }
   ]
  },
  {
   "title": "Aborts by Event Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_rule_aborts_total{job=\"$device_name\", f5_rule_name=~\"$rule\"}",
     "legendFormat": "{{f5_rule_name}} - {{f5_rule_event_type}}"
    }
   ]
  }
 ]
}