{
 "title": "Device Virtual Server",
 "description": "Drill-Down Details for a Single Virtual Server",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "query": {
     "query": "label_values(f5_system_state_up_ratio,job)"
    }
   },
   {
    "name": "virtual_server",
    "query": {
     "query": "label_values(f5_virtual_server_info{job=\"$device_name\"},f5_virtual_server_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VS Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "f5_virtual_server_info{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generation Changes [24h]",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "changes(f5_virtual_server_generation{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Virtual Server State isAvailable",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(f5_virtual_server_availability_ratio{job=\"$device_name\", availability_state=\"available\", f5_virtual_server_name=~\"$virtual_server\"}[$__interval])",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  {
   "title": "Virtual Server isEnabled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(f5_virtual_server_enabled_ratio{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__interval])",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  {
   "title": "Virtual Server Availability [24h]",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", availability_state=\"available\", f5_virtual_server_name=~\"$virtual_server\"}[24h]) / count_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"available\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"offline\"}[24h]) / count_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"offline\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"unknown\"}[24h]) / count_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"unknown\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_virtual_server_enabled_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[24h]) / count_over_time(f5_virtual_server_enabled_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Configured Objects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Server Pool State",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "f5_virtual_server_info{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", f5_pool_name!=\"\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "f5_pool_availability_ratio{job=\"$device_name\"}==1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Applied iRules",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "expr": "f5_virtual_server_rule_enabled_ratio{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Applied Profiles",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "expr": "f5_virtual_server_profile_info{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Server CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "f5_virtual_server_cpu_utilization_5s{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}",
       "legendFormat": "{{f5_virtual_server_name}}"
      }
     ]
    },
    {
     "title": "Virtual Server ASM CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "f5_virtual_server_asm_cpu_utilization_percent{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}",
       "legendFormat": "{{f5_virtual_server_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Server Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(f5_virtual_server_requests_total{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
       "legendFormat": "{{f5_virtual_server_name}}"
      }
     ]
    },
    {
     "title": "Virtual Server Traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "8 * rate(f5_virtual_server_clientside_bytes_in_total{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
       "legendFormat": "{{f5_virtual_server_name}} - In"
      },
      {
       "expr": "-8 * rate(f5_virtual_server_clientside_bytes_out_total{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
       "legendFormat": "{{f5_virtual_server_name}} - Out"
      }
     ]
    },
    {
     "title": "Virtual Server Packets Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(f5_virtual_server_packets_in_total{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
       "legendFormat": "{{f5_virtual_server_name}} - In"
      },
      {
       "expr": "-1 * rate(f5_virtual_server_packets_out_total{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
       "legendFormat": "{{f5_virtual_server_name}} - Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Server Concurrent Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "f5_virtual_server_clientside_connection_count{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}",
       "legendFormat": "{{f5_virtual_server_name}}"
      }
     ]
    },
    {
     "title": "Virtual Server Connection Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "C/s" } },
     "targets": [
      {
       "expr": "rate(f5_virtual_server_clientside_connection_total{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
       "legendFormat": "{{f5_virtual_server_name}}"
      }
     ]
    },
    {
     "title": "Virtual Server Avg. Connection Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "f5_virtual_server_clientside_connection_duration_mean_milliseconds{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}",
       "legendFormat": "{{f5_virtual_server_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests & Responses/Sec",
     "type": "timeseries",
     "description": "HTTP Requests by Virtual Server",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum by(f5_virtual_server_name) (rate(f5_virtual_server_profile_http_requests_by_method_total{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval]))",
       "legendFormat": "{{f5_virtual_server_name}} - Requests"
      },
      {
       "expr": "sum by(f5_virtual_server_name) (rate(f5_virtual_server_profile_http_responses_by_status_total{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval]))",
       "legendFormat": "{{f5_virtual_server_name}} - Responses"
      }
     ]
    },
    {
     "title": "HTTP Responses/Sec",
     "type": "timeseries",
     "description": "HTTP Responses by Virtual Server",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "rate(f5_virtual_server_profile_http_responses_by_status_total{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", http_status_range=\"2xx\"}[$__rate_interval])",
       "legendFormat": "{{f5_virtual_server_name}} - 2xx"
      },
      {
       "expr": "sum by(f5_virtual_server_name) (rate(f5_virtual_server_profile_http_responses_by_status_total{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", http_status_range!=\"2xx\"}[$__rate_interval]))",
       "legendFormat": "{{f5_virtual_server_name}} - Other"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      { "expr": "f5_profile_dns_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "DNS Latencies (msec.)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "f5_profile_dns_client_hits_response_time_milliseconds{job=~\"$device_name\"}",
       "legendFormat": "{{f5_profile_dns_name}} - Hits"
      },
      {
       "expr": "f5_profile_dns_client_misses_response_time_milliseconds{job=~\"$device_name\"}",
       "legendFormat": "{{f5_profile_dns_name}} - Misses"
      }
     ]
    },
    {
     "title": "DNS Queries & Responses/Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum by(f5_profile_dns_name) (rate(f5_profile_dns_request_total{job=~\"$device_name\"}[$__rate_interval]))",
       "legendFormat": "{{f5_profile_dns_name}} - Requests"
      },
      {
       "expr": "sum by(f5_profile_dns_name) (rate(f5_profile_dns_response_total{job=~\"$device_name\"}[$__rate_interval]))",
       "legendFormat": "{{f5_profile_dns_name}} - Responses"
      }
     ]
    },
    {
     "title": "DNS Express Queries & Responses/Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sum by(f5_profile_dns_name) (rate(f5_profile_dns_dnsx_queries_total{job=~\"$device_name\"}[$__rate_interval]))",
       "legendFormat": "{{f5_profile_dns_name}} - Queries"
      },
      {
       "expr": "sum by(f5_profile_dns_name) (rate(f5_profile_dns_dnsx_responses_total{job=\"$device_name\"}[$__rate_interval]))",
       "legendFormat": "{{f5_profile_dns_name}} - Responses"
      }
     ]
    }
   ]
  },
  {
   "title": "SSL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "SSL Bytes/Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by(f5_virtual_server_name) (rate(f5_virtual_server_profile_client_ssl_bytes_in_total{f5_virtual_server_name=~\"$virtual_server\", job=~\"$device_name\"}[$__rate_interval]))",
       "legendFormat": "{{f5_virtual_server_name}} - Inbound"
      },
      {
       "expr": " - sum by(f5_virtual_server_name) (rate(f5_virtual_server_profile_client_ssl_bytes_out_total{f5_virtual_server_name=~\"$virtual_server\", job=~\"$device_name\"}[$__rate_interval]))",
       "legendFormat": "{{f5_virtual_server_name}} - Outbound"
      }
     ]
    },
    {
     "title": "SSL Handshakes & Renegotiations/Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum by(f5_virtual_server_name) (rate(f5_virtual_server_profile_client_ssl_renegotiations_total{f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval]))",
       "legendFormat": "{{f5_virtual_server_name}} - Renegotiiations"
      },
      {
       "expr": "sum by(f5_virtual_server_name) (rate(f5_virtual_server_profile_client_ssl_secure_handshakes_total{f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval]))",
       "legendFormat": "{{f5_virtual_server_name}} - Handshakes"
      }
     ]
    }
   ]
  }
 ]
}