{
 "title": "Device Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_system_state_up_ratio,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Device Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_state_up_ratio{job=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "f5_system_info{job=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "License State",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 1 },
   "targets": [
    { "expr": "f5_module_license_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Enabled Modules",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "f5_module_provision_generation{level!=\"none\", job=~\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failover Peer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_failover_peer_active_state_ratio{job=\"$device_name\"}",
     "legendFormat": "{{failover_peer_name}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_info{job=\"$device_name\"}",
     "legendFormat": "{{system_version}}"
    }
   ]
  },
  { "title": "Device Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "f5_system_cpu_utilization_ratio{job=\"$device_name\"}",
     "legendFormat": "Slot: {{slot_id}} CPU: {{cpu_id}}"
    }
   ]
  },
  {
   "title": "SubSystem CPU Utilization",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_subsystem_cpu_utilization_ratio{job=\"$device_name\"}",
     "legendFormat": "{{f5_subsystem_name}}"
    },
    {
     "expr": "sum(1-f5_system_cpu_utilization_ratio{job=\"$device_name\"})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Top 10 Process By CPU",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(f5_system_process_cpu_top_10_ratio{job=\"$device_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. CPU Utilization ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_system_cpu_utilization_ratio{job=\"$device_name\"}) / count(f5_system_cpu_utilization_ratio{job=\"$device_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_memory_used_bytes{job=\"$device_name\", state=\"used\"} / ignoring(state) f5_system_memory_total_bytes{job=\"$device_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "f5_system_memory_used_bytes{job=\"$device_name\", state=\"used\"} / ignoring(state) f5_system_memory_total_bytes{job=\"$device_name\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "SubSystem Memory Utilization",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_subsystem_memory_resident_used_bytes{job=\"$device_name\"}",
     "legendFormat": "{{f5_subsystem_name}}"
    },
    {
     "expr": "f5_system_memory_used_bytes{state=\"free\", job=\"$device_name\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Top 10 Process By Memory",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(f5_system_process_memory_top_10_bytes{job=\"$device_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Use",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(f5_system_logical_disk_application_used_bytes{job=\"$device_name\"})",
     "legendFormat": "{{f5_system_logical_disk_name}} / {{f5_system_logical_disk_application_name}}"
    },
    {
     "expr": "sum(f5_system_logical_disk_limit_bytes{job=\"$device_name\"}) by(f5_system_logical_disk_name) - sum(f5_system_logical_disk_usage_bytes{job=\"$device_name\", state=~\"free\"} * 1000000) by (f5_system_logical_disk_name) - sum(f5_system_logical_disk_application_used_bytes{job=\"$device_name\"}) by (f5_system_logical_disk_name)",
     "legendFormat": "{{f5_system_logical_disk_name}} / Other"
    },
    {
     "expr": "f5_system_logical_disk_usage_bytes{job=\"$device_name\", state=~\"free\"} * 1000000",
     "legendFormat": "{{f5_system_logical_disk_name}} / Free"
    }
   ]
  },
  { "title": "Device Virtual Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "VS Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "f5_virtual_server_cpu_utilization_5s{job=\"$device_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "f5_virtual_server_enabled_ratio{job=\"$device_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "f5_virtual_server_info{job=~\"$device_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "f5_virtual_server_availability_ratio{job=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VS Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(f5_virtual_server_clientside_bytes_in_total{job=\"$device_name\"}[$__rate_interval]) * 8",
     "legendFormat": "{{f5_virtual_server_name}} - In"
    },
    {
     "expr": "rate(f5_virtual_server_clientside_bytes_out_total{job=\"$device_name\"}[$__rate_interval]) * -8",
     "legendFormat": "{{f5_virtual_server_name}} - Out"
    }
   ]
  },
  {
   "title": "VS Concurrent Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "f5_virtual_server_clientside_connection_count{job=\"$device_name\"}",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  { "title": "Device Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Network Addresses",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "f5_network_address_info{job=~\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Interface Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(f5_network_interface_bits_in_total{job=~\"$device_name\"}[$__rate_interval])",
     "legendFormat": "Int: {{f5_network_interface_name}} (In)"
    },
    {
     "expr": "rate(f5_network_interface_bits_out_total{job=~\"$device_name\"}[$__rate_interval]) * -1",
     "legendFormat": "Int: {{f5_network_interface_name}} (Out)"
    }
   ]
  },
  {
   "title": "VLAN Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "f5_network_vlan_info{job=~\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Interface Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(f5_network_interface_errors_total{job=~\"$device_name\"}[$__rate_interval])",
     "legendFormat": "Int: {{f5_network_interface_name}}"
    }
   ]
  }
 ]
}