{
 "title": "Top N",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_system_state_up_ratio,job)"
    }
   },
   { "name": "N", "query": "10" }
  ]
 },
 "panels": [
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 10 VIPs By CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, f5_virtual_server_cpu_utilization_5s{job=~\"$device_name\"})",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Process By CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(f5_system_process_cpu_top_10_ratio{job=\"$device_name\"})",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Analysis, Control, Data Plane Utilization",
   "type": "timeseries",
   "description": "This panel requires data retrieved from a bash command. If the BigIP account used to scrape the device lacks this permission, it is expected to be blank.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "f5_plane_cpu_utilization_5s{job=~\"$device_name\"}",
     "legendFormat": "{{plane}}"
    }
   ]
  },
  {
   "title": "Top 10 VIPs By WAF CPU Utilization",
   "type": "timeseries",
   "description": "This panel requires data retrieved from a bash command. If the BigIP account used to scrape the device lacks this permission, it is expected to be blank.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, f5_virtual_server_asm_cpu_utilization_percent{job=~\"$device_name\"})",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  { "title": "Top Pools / Members", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Top $N Pools By Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk($N, f5_pool_connection_count{job=\"$device_name\"})",
     "legendFormat": "{{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "Top $N Pool Members By Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "topk($N, f5_pool_member_connection_count{job=\"$device_name\"})",
     "legendFormat": "Pool: {{f5_pool_name}} Member: {{f5_pool_member_name}}"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Top $N Virtual Servers By Low Availability [24h]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk($N, sum_over_time(f5_virtual_server_availability_ratio{job=\"$device_name\",availability_state=\"available\"}[24h]) / count_over_time(f5_virtual_server_availability_ratio{job=\"$device_name\",availability_state=\"available\"}[24h]))",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  {
   "title": "Top $N Virtual Servers By Low Availability [14d]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk($N, sum_over_time(f5_virtual_server_availability_ratio{job=\"$device_name\",availability_state=\"available\"}[14d]) / count_over_time(f5_virtual_server_availability_ratio{job=\"$device_name\",availability_state=\"available\"}[14d]))",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  {
   "title": "Top $N Pools By Low Availability [24h]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk($N, sum_over_time(f5_pool_availability_ratio{job=\"$device_name\",availability_state=\"available\"}[24h]) / count_over_time(f5_pool_availability_ratio{job=\"$device_name\",availability_state=\"available\"}[24h]))",
     "legendFormat": "{{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "Top $N Pools By Low Availability [14d]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk($N, sum_over_time(f5_pool_availability_ratio{job=\"$device_name\",availability_state=\"available\"}[14d]) / count_over_time(f5_pool_availability_ratio{job=\"$device_name\",availability_state=\"available\"}[14d]))",
     "legendFormat": "{{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "Top $N Pool Members By Low Availability [24h]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk($N, sum_over_time(f5_pool_member_availability_ratio{job=\"$device_name\",availability_state=\"available\"}[24h]) / count_over_time(f5_pool_member_availability_ratio{job=\"$device_name\",availability_state=\"available\"}[24h]))",
     "legendFormat": "{{f5_pool_member_name}}"
    }
   ]
  },
  {
   "title": "Top $N Pool Members By Low Availability [14d]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk($N, sum_over_time(f5_pool_member_availability_ratio{job=\"$device_name\",availability_state=\"available\"}[14d]) / count_over_time(f5_pool_member_availability_ratio{job=\"$device_name\",availability_state=\"available\"}[14d]))",
     "legendFormat": "{{f5_pool_member_name}}"
    }
   ]
  },
  { "title": "Top VIPs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Top $N VIPs By SSL TPS Utilization",
   "type": "timeseries",
   "description": "This panel requires data retrieved from a bash command. If the BigIP account used to scrape the device lacks this permission, it is expected to be blank.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "topk($N, rate(f5_virtual_server_profile_client_ssl_records_in_total{job=\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "Virtual Server: {{f5_virtual_server_name}} Profile: {{f5_profile_client_ssl_name}}"
    }
   ]
  },
  {
   "title": "Top $N VIPs By Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * topk($N, rate(f5_virtual_server_clientside_bytes_in_total{job=\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{f5_virtual_server_name}} - In"
    },
    {
     "expr": " -8 * topk(10, rate(f5_virtual_server_clientside_bytes_out_total{job=\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{f5_virtual_server_name}} - Out"
    }
   ]
  },
  {
   "title": "Top $N VIPs By Object Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "topk($N, sort_desc(f5_virtual_server_configured_object_count{job=~\"$device_name\"}))",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  {
   "title": "Top $N VIP Applied Profile Types ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "topk($N, sort_desc(count by(f5_profile_family, f5_profile_type) (f5_virtual_server_profile_info{job=\"$device_name\"})))",
     "legendFormat": "{{f5_profile_family}}/{{f5_profile_type}}"
    }
   ]
  },
  { "title": "iRule Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Top 10 iRules By Cycles Per Execution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "topk(10, max by(f5_rule_name) (f5_rule_average_cycles{job=\"$device_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 iRules By Execution Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, max by(f5_rule_name) (f5_rule_executions_total{job=\"$device_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 iRules By Approx. Cycles Used [24h]",
   "type": "barchart",
   "description": "(Average Cycles / Execution) *E(xecutions Last 24 Hours)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "topk(10, max by(f5_rule_name) (f5_rule_average_cycles{job=\"$device_name\"}) * max by(f5_rule_name) (increase(f5_rule_executions_total{job=\"$device_name\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}